// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.se;

import com.se.Name;

privileged aspect Name_Roo_JavaBean {
    
    public String Name.getName() {
        return this.name;
    }
    
    public void Name.setName(String name) {
        this.name = name;
    }
    
}
